database:
    # sqlite|mysql
    use:       sqlite
    # MYSQL
    host:      localhost
    user:      root
    passwd:    root
    db:        jokes
    table:     jokes_fr_cat
    # SQLITE
    sqlite:    /home/laurent/Documents/PyJoke/JOKES.db
postag:
    active:    0
    default:   1
    adj:       2
    noun:      4
    verb:      2
    #if active, will ignore "default" words
    brute:     1
pyjoke:
    #For removing stopwords
    lang:      french
    #Max length for joke
    jokelen:   100
    debug:     0
conversation:
    level:     0
    history:   0
